/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AboutButton: typeof import('./src/components/FloatingButtons/AboutButton.vue')['default']
    Accordion: typeof import('primevue/accordion')['default']
    AccordionContent: typeof import('primevue/accordioncontent')['default']
    AccordionHeader: typeof import('primevue/accordionheader')['default']
    AccordionPanel: typeof import('primevue/accordionpanel')['default']
    AutoComplete: typeof import('primevue/autocomplete')['default']
    AvoidRushHourSwitch: typeof import('./src/components/AppBar/TimetableSettings/AvoidRushHourSwitch.vue')['default']
    BuildTimetableButton: typeof import('./src/components/AppBar/BuildTimetableButton.vue')['default']
    Button: typeof import('primevue/button')['default']
    Carousel: typeof import('primevue/carousel')['default']
    ChangeSessionGroup: typeof import('./src/components/Popup/ChangeSessionGroup.vue')['default']
    ChangeTheme: typeof import('./src/components/AppBar/ChangeTheme.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    Column: typeof import('primevue/column')['default']
    CourseDetailCardsLayer: typeof import('./src/components/CourseDetails/CourseDetailCardsLayer.vue')['default']
    CourseDetailsPopup: typeof import('./src/components/CourseDetails/CourseDetailsPopup.vue')['default']
    CourseDetailsSectionCard: typeof import('./src/components/CourseDetails/CourseDetailsSectionCard.vue')['default']
    CourseSearchBar: typeof import('./src/components/AppBar/CourseSearchBar.vue')['default']
    CourseTimetable: typeof import('./src/components/CourseDetails/CourseTimetable.vue')['default']
    DataTable: typeof import('primevue/datatable')['default']
    Dialog: typeof import('primevue/dialog')['default']
    Divider: typeof import('primevue/divider')['default']
    DivisionalLegend: typeof import('./src/components/CourseDetails/DivisionalLegend.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    EnrolmentLegendPopup: typeof import('./src/components/CourseDetails/EnrolmentLegendPopup.vue')['default']
    ExportCalendarButton: typeof import('./src/components/FloatingButtons/ExportCalendarButton.vue')['default']
    ExportTimetableTemplate: typeof import('./src/components/FloatingButtons/ExportTimetableTemplate.vue')['default']
    HelpDial: typeof import('./src/components/FloatingButtons/HelpDial.vue')['default']
    HourSwitch: typeof import('./src/components/Timetable/HourSwitch.vue')['default']
    IncludeUnavailableSwitch: typeof import('./src/components/AppBar/TimetableSettings/IncludeUnavailableSwitch.vue')['default']
    InputNumber: typeof import('primevue/inputnumber')['default']
    MaxContinuousHoursInput: typeof import('./src/components/AppBar/TimetableSettings/MaxContinuousHoursInput.vue')['default']
    MaxDayLengthInput: typeof import('./src/components/AppBar/TimetableSettings/MaxDayLengthInput.vue')['default']
    MaxGapInput: typeof import('./src/components/AppBar/TimetableSettings/MaxGapInput.vue')['default']
    MinDayLengthInput: typeof import('./src/components/AppBar/TimetableSettings/MinDayLengthInput.vue')['default']
    MiscSettingsGroup: typeof import('./src/components/AppBar/TimetableSettings/MiscSettingsGroup.vue')['default']
    NoTimetablePopup: typeof import('./src/components/Popup/NoTimetablePopup.vue')['default']
    OnlinePreferenceSelect: typeof import('./src/components/AppBar/TimetableSettings/OnlinePreferenceSelect.vue')['default']
    OverwriteLockedSectionPopup: typeof import('./src/components/Popup/OverwriteLockedSectionPopup.vue')['default']
    Popover: typeof import('primevue/popover')['default']
    PrefferedGapSettingsGroup: typeof import('./src/components/AppBar/TimetableSettings/PrefferedGapSettingsGroup.vue')['default']
    PrefferedTimeSettingsGroup: typeof import('./src/components/AppBar/TimetableSettings/PrefferedTimeSettingsGroup.vue')['default']
    RadioButton: typeof import('primevue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchDivisionSelect: typeof import('./src/components/AppBar/SearchSettings/SearchDivisionSelect.vue')['default']
    SearchSessionSelect: typeof import('./src/components/AppBar/SearchSettings/SearchSessionSelect.vue')['default']
    SearchSettings: typeof import('./src/components/AppBar/SearchSettings/SearchSettings.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    SelectedCourseCard: typeof import('./src/components/SidePanel/SelectedCourseCard.vue')['default']
    SelectedCoursesPanel: typeof import('./src/components/SidePanel/SelectedCoursesPanel.vue')['default']
    SessionSelect: typeof import('./src/components/AppBar/SessionSelect.vue')['default']
    SideBar: typeof import('./src/components/SidePanel/SideBar.vue')['default']
    TextDivider: typeof import('./src/components/Misc/TextDivider.vue')['default']
    TimeSettingSelect: typeof import('./src/components/AppBar/TimetableSettings/TimeSettingSelect.vue')['default']
    Timetable: typeof import('./src/components/Timetable/Timetable.vue')['default']
    TimetableEvent: typeof import('./src/components/Timetable/TimetableEvent.vue')['default']
    TimetableSettingsMenu: typeof import('./src/components/AppBar/TimetableSettings/TimetableSettingsMenu.vue')['default']
    Toast: typeof import('primevue/toast')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    TutorialButton: typeof import('./src/components/FloatingButtons/TutorialButton.vue')['default']
    TutorialPopup: typeof import('./src/components/Popup/TutorialPopup.vue')['default']
    WeekdaySwitch: typeof import('./src/components/Timetable/WeekdaySwitch.vue')['default']
  }
  export interface GlobalDirectives {
    Ripple: typeof import('primevue/ripple')['default']
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
